### ISSUE TITLE
Issue with CollectionControl and parent item

### ISSUE THREAD

**Issue by PavloParafiloCricut** [peterrexj/Selenium.Essentials#27]
Looks like CollectionControl doesn't respect parentControl parameter. Even passing parent it still founds first on a page
```
WebControl updateContainer = new CollectionControl(Driver, By.ClassName("some-class"),  parentControl)
   .Item(1);
```

**Comment by peterrexj** [comment]
Hi @PavloParafiloCricut, I totally missed this, thanks for reporting the problem, I have fixed it in the latest version and added a couple of more features to the CollectionControl and other controls

https://www.nuget.org/packages/Selenium.Essentials/1.0.5.11

- CollectionControl - Fix issue when search or operations were not considering the parent control
- CollectionControl - VisibleItem<control> at position - returns the item/element/control visible at the position
- CollectionControl - FirstVisibleControl<control> - returns the first visible item/element/control from the collection
- CollectionControl - FirstVisibleElement - returns element/control of type WebControl which is first visible in the collection
- CollectionControl - DoubleClick(position) - performs double click on the control at position
- CollectionControl - WaitForMinimumOne(position) - waits for the control/element at specified position is available
- AllControls - NotExists - bool to return if the element does not exist and is available for all controls
- AllControls - DoubleClick - performs double click and is available for all controls

Please let me know if that works and also if you see more issues, happy to help,

Thanks,
Peter
